apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z joomla-db 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: joomla
          image: localhost:32000/joomla
          ports:
            - containerPort: 80
          env:
            - name: JOOMLA_DB_HOST
              value: joomla-db
            - name: JOOMLA_DB_NAME
              value: joomla
            - name: JOOMLA_DB_USER
              value: joomla
            - name: JOOMLA_DB_PASSWORD
              value: parola123
